# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Release latest changes
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  workflow_dispatch:
jobs:
  infrastruct:
    name: Infrastructural adaptations
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tullius
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Install a flaked Nix
        uses: DeterminateSystems/nix-installer-action@v13
      - name: Restore or save caches
        uses: DeterminateSystems/magic-nix-cache-action@v8
      - name: Prepare for structure
        run: nix run .#tofu -- init
      - name: Ensure sensible setup
        run: |
          nix run .#tofu -- fmt -check
          nix run .#tofu -- validate
      - name: Plan the upcoming change
        if: github.event_name == 'pull_request'
        run: nix run .#tofu -- plan
      - name: Actually apply the change
        if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
        run: nix run .#tofu -- apply -auto-approve
