# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Release latest changes
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  workflow_dispatch:
jobs:
  infrastruct:
    name: Infrastructural adaptations
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: tullius
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout this repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Install a flaked Nix
        uses: DeterminateSystems/nix-installer-action@21a544727d0c62386e78b4befe52d19ad12692e3 # v17
      - name: Prepare for structure
        run: nix run .#tullius.tofu -- init
      - name: Ensure sensible setup
        run: |
          nix run .#tullius.tofu -- fmt -check
          nix run .#tullius.tofu -- validate
      - name: Plan the upcoming change
        if: github.event_name == 'pull_request'
        run: nix run .#tullius.tofu -- plan
      - name: Actually apply the change
        if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
        run: nix run .#tullius.tofu -- apply -auto-approve
