# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: License update
on:
  schedule:
    - cron: "0 0 27 12 *"
  workflow_dispatch:
jobs:
  licensure:
    name: Cheers
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout this repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: true
      - name: Configure git credentials
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
      - name: Increment the latter year
        run: |
          git pull
          git checkout -b chore-renew-license || git checkout chore-renew-license
          sed -i -E "s/(2[0-9]{3})(-2[0-9]{3})?/\1-$(date -d 'next year' +'%Y')/" LICENSE
      - name: Commit to open source
        run: |
          git add LICENSE
          git commit -m "chore(license): update end year to include $(date -d 'next year' +'%Y')"
          git push -u origin chore-renew-license
          gh pr create \
            --title "chore(license): update end year to include $(date -d 'next year' +'%Y')" \
            --body ":tada:"
        env:
          GH_TOKEN: ${{ github.token }}
